name: build documentation

on: [push, pull_request]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: documentation
          root_file: main.tex
          texlive_version: 2023

      - name: export pdf file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: docs/main.pdf
